### ISSUE TITLE
Making it available as "API"

### ISSUE THREAD

**Issue by chez14** [ftisunpar/data#1]
Hi,

I wanted to use this for https://github.com/ftis-admin/oxam-bleh, as all Kode Mata Kuliah changed, so i need to regenerate a new one, and this list can provide data in dynamic way if it's served as accessable file.

I think by serving it using GitHub Page is enough, as it can be accessed via https://ftisunpar.github.io/data/prasyarat.json, and GH does support CORS now. So other Js app can casually do call ajax to that link and got the data they wanted.

What do you think with this feature proposal? Thank you.

More ref for this proposal:
- GitHub page support CORS: https://stackoverflow.com/a/26417091/4721245

**Comment by pascalalfadian** [comment]
Hi Chris,

I just turned on github page so your link works now: https://ftisunpar.github.io/data/prasyarat.json

Is that enough? If not, please send PR or ask me in this issue.

Of course I am very happy if this data can be used, that's the point of opening this data. Note that the data is not final, though the format is kind of final.

**Comment by chez14** [comment]
> Is that enough? If not, please send PR or ask me in this issue.

This is cukup-enough, Thank you! :+1:

> Of course I am very happy if this data can be used, that's the point of opening this data. Note that the data is not final, though the format is kind of final.

Ok, noted very well
